// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4K-jC3awjKPSXUWKllBQJVGnC5-Wd12M',
    appId: '1:134756462663:web:51dd1b8a4ee0bbdc658162',
    messagingSenderId: '134756462663',
    projectId: 'cmsc-23-b-2l-kmcelestino',
    authDomain: 'cmsc-23-b-2l-kmcelestino.firebaseapp.com',
    storageBucket: 'cmsc-23-b-2l-kmcelestino.appspot.com',
    measurementId: 'G-HKED2YXNMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzPxIu7FpyHBLlAxq_83k7WlKLtGMnQlE',
    appId: '1:134756462663:android:517b15b5f459aee1658162',
    messagingSenderId: '134756462663',
    projectId: 'cmsc-23-b-2l-kmcelestino',
    storageBucket: 'cmsc-23-b-2l-kmcelestino.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTvfEME6zJ6m9TGsFHSfNxn4VnFA1F0Xc',
    appId: '1:134756462663:ios:dcab269a10500f20658162',
    messagingSenderId: '134756462663',
    projectId: 'cmsc-23-b-2l-kmcelestino',
    storageBucket: 'cmsc-23-b-2l-kmcelestino.appspot.com',
    iosClientId: '134756462663-sl9766806kisjm98v95sn2530fb7vfkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTvfEME6zJ6m9TGsFHSfNxn4VnFA1F0Xc',
    appId: '1:134756462663:ios:dcab269a10500f20658162',
    messagingSenderId: '134756462663',
    projectId: 'cmsc-23-b-2l-kmcelestino',
    storageBucket: 'cmsc-23-b-2l-kmcelestino.appspot.com',
    iosClientId: '134756462663-sl9766806kisjm98v95sn2530fb7vfkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
